"""empty message

Revision ID: 0cb882b1a8db
Revises: 
Create Date: 2026-06-13 17:30:01.370020
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cb882b1a8db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('article_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_code', sa.String(length=30), nullable=False),
    sa.Column('asset_label', sa.String(length=100), nullable=False),
    sa.Column('price_per_gram', sa.BigInteger(), nullable=False),
    sa.Column('stale_after_minutes', sa.Integer(), nullable=False),
    sa.Column('auto_update', sa.Boolean(), nullable=True),
    sa.Column('update_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_code')
    )
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(), nullable=False),
    sa.Column('melt_number', sa.String(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('purity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_number')
    )
    op.create_table('dealer_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_end_customer', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('default_credit_limit_mg', sa.BigInteger(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('geo_provinces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gift_boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('metal_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metal_type', sa.String(length=20), nullable=False),
    sa.Column('balance_mg', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metal_type')
    )
    op.create_table('package_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('query_string', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_display', sa.String(length=200), nullable=True),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reqlog_created', 'request_logs', ['created_at'], unique=False)
    op.create_index('ix_reqlog_ip', 'request_logs', ['ip_address'], unique=False)
    op.create_index('ix_reqlog_method', 'request_logs', ['method'], unique=False)
    op.create_index('ix_reqlog_path', 'request_logs', ['path'], unique=False)
    op.create_index('ix_reqlog_user_type', 'request_logs', ['user_type'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('system_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('avatar_path', sa.String(), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('otp_code', sa.String(), nullable=True),
    sa.Column('otp_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_users_mobile'), 'system_users', ['mobile'], unique=True)
    op.create_table('testimonials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_name', sa.String(length=200), nullable=False),
    sa.Column('person_title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('avatar_path', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batch_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_images_batch_id'), 'batch_images', ['batch_id'], unique=False)
    op.create_table('geo_cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['province_id'], ['geo_provinces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_cities_province_id'), 'geo_cities', ['province_id'], unique=False)
    op.create_table('gift_box_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('gift_box_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gift_box_id'], ['gift_boxes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_box_images_gift_box_id'), 'gift_box_images', ['gift_box_id'], unique=False)
    op.create_table('package_type_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['package_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_type_images_package_id'), 'package_type_images', ['package_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('purity', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('wage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('buyback_wage_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_wage_percent', sa.Boolean(), nullable=False),
    sa.Column('metal_type', sa.String(length=20), nullable=False),
    sa.Column('package_type_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.CheckConstraint('buyback_wage_percent >= 0', name='ck_product_buyback_wage_nonneg'),
    sa.CheckConstraint('purity > 0 AND purity <= 999.9', name='ck_product_purity_range'),
    sa.CheckConstraint('wage >= 0', name='ck_product_wage_nonneg'),
    sa.CheckConstraint('weight > 0', name='ck_product_weight_positive'),
    sa.ForeignKeyConstraint(['package_type_id'], ['package_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_package_type_id'), 'products', ['package_type_id'], unique=False)
    op.create_table('geo_districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['geo_cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_districts_city_id'), 'geo_districts', ['city_id'], unique=False)
    op.create_table('product_category_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'category_id', name='uq_product_category_link')
    )
    op.create_index(op.f('ix_product_category_links_category_id'), 'product_category_links', ['category_id'], unique=False)
    op.create_index(op.f('ix_product_category_links_product_id'), 'product_category_links', ['product_id'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_table('product_package_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('package_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_type_id'], ['package_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'package_type_id', name='uq_product_package_link')
    )
    op.create_index(op.f('ix_product_package_links_package_type_id'), 'product_package_links', ['package_type_id'], unique=False)
    op.create_index(op.f('ix_product_package_links_product_id'), 'product_package_links', ['product_id'], unique=False)
    op.create_table('product_tier_wages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('wage_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tier_id'], ['dealer_tiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'tier_id', name='uq_product_tier_wage')
    )
    op.create_index(op.f('ix_product_tier_wages_product_id'), 'product_tier_wages', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_tier_wages_tier_id'), 'product_tier_wages', ['tier_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.String(length=11), nullable=False),
    sa.Column('national_id', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('avatar_path', sa.String(), nullable=True),
    sa.Column('otp_code', sa.String(), nullable=True),
    sa.Column('otp_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_dealer', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('customer_type', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('economic_code', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('referral_code', sa.String(length=10), nullable=True),
    sa.Column('referred_by', sa.Integer(), nullable=True),
    sa.Column('referral_rewarded', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('shahkar_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('shahkar_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tier_id', sa.Integer(), nullable=True),
    sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_warehouse', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_postal_hub', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_distribute', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_central_warehouse', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('dealer_address', sa.Text(), nullable=True),
    sa.Column('dealer_postal_code', sa.String(length=10), nullable=True),
    sa.Column('landline_phone', sa.String(length=15), nullable=True),
    sa.Column('api_key', sa.String(length=64), nullable=True),
    sa.Column('rasis_sharepoint', sa.Integer(), nullable=True),
    sa.Column('rasis_last_record_version', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('custom_credit_limit_mg', sa.BigInteger(), nullable=True),
    sa.Column('admin_role', sa.String(), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['geo_cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['geo_districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['province_id'], ['geo_provinces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referred_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tier_id'], ['dealer_tiers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    op.create_index(op.f('ix_users_city_id'), 'users', ['city_id'], unique=False)
    op.create_index('ix_users_created', 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_district_id'), 'users', ['district_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)
    op.create_index(op.f('ix_users_is_dealer'), 'users', ['is_dealer'], unique=False)
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    op.create_index(op.f('ix_users_national_id'), 'users', ['national_id'], unique=True)
    op.create_index(op.f('ix_users_province_id'), 'users', ['province_id'], unique=False)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_users_tier_id'), 'users', ['tier_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_code', sa.String(), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('locked_balance', sa.BigInteger(), nullable=False),
    sa.Column('credit_balance', sa.BigInteger(), nullable=False),
    sa.Column('credit_limit_mg', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('balance >= -credit_limit_mg', name='ck_account_balance_with_credit'),
    sa.CheckConstraint('credit_balance >= 0', name='ck_account_credit_nonneg'),
    sa.CheckConstraint('locked_balance >= 0', name='ck_account_locked_nonneg'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'asset_code', name='uq_account_user_asset')
    )
    op.create_index('ix_account_user_asset', 'accounts', ['user_id', 'asset_code'], unique=False)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['article_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_article_status_published', 'articles', ['status', 'published_at'], unique=False)
    op.create_index(op.f('ix_articles_author_id'), 'articles', ['author_id'], unique=False)
    op.create_index(op.f('ix_articles_category_id'), 'articles', ['category_id'], unique=False)
    op.create_table('bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_code', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('claim_code', sa.String(length=8), nullable=True),
    sa.Column('reserved_customer_id', sa.Integer(), nullable=True),
    sa.Column('reserved_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_preorder', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dealer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reserved_customer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bars_batch_id'), 'bars', ['batch_id'], unique=False)
    op.create_index(op.f('ix_bars_claim_code'), 'bars', ['claim_code'], unique=True)
    op.create_index(op.f('ix_bars_customer_id'), 'bars', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bars_dealer_id'), 'bars', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_bars_id'), 'bars', ['id'], unique=False)
    op.create_index(op.f('ix_bars_product_id'), 'bars', ['product_id'], unique=False)
    op.create_index(op.f('ix_bars_serial_code'), 'bars', ['serial_code'], unique=True)
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('coupon_type', sa.String(), nullable=False),
    sa.Column('discount_mode', sa.String(), nullable=False),
    sa.Column('discount_value', sa.BigInteger(), nullable=False),
    sa.Column('max_discount_amount', sa.BigInteger(), nullable=True),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('scope_product_id', sa.Integer(), nullable=True),
    sa.Column('scope_category', sa.String(), nullable=True),
    sa.Column('min_order_amount', sa.BigInteger(), nullable=False),
    sa.Column('max_order_amount', sa.BigInteger(), nullable=True),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('max_total_uses', sa.Integer(), nullable=True),
    sa.Column('max_per_customer', sa.Integer(), nullable=False),
    sa.Column('current_uses', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_purchase_only', sa.Boolean(), nullable=False),
    sa.Column('is_combinable', sa.Boolean(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('referrer_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('current_uses >= 0', name='ck_coupon_current_uses_nonneg'),
    sa.CheckConstraint('discount_value >= 0', name='ck_coupon_discount_value_nonneg'),
    sa.CheckConstraint('min_order_amount >= 0', name='ck_coupon_min_order_nonneg'),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scope_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coupon_code_status', 'coupons', ['code', 'status'], unique=False)
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_index(op.f('ix_coupons_referrer_user_id'), 'coupons', ['referrer_user_id'], unique=False)
    op.create_index(op.f('ix_coupons_scope_product_id'), 'coupons', ['scope_product_id'], unique=False)
    op.create_table('customer_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('receiver_name', sa.String(), nullable=True),
    sa.Column('receiver_phone', sa.String(length=15), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['geo_cities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['district_id'], ['geo_districts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['province_id'], ['geo_provinces.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_addresses_city_id'), 'customer_addresses', ['city_id'], unique=False)
    op.create_index(op.f('ix_customer_addresses_district_id'), 'customer_addresses', ['district_id'], unique=False)
    op.create_index(op.f('ix_customer_addresses_province_id'), 'customer_addresses', ['province_id'], unique=False)
    op.create_index(op.f('ix_customer_addresses_user_id'), 'customer_addresses', ['user_id'], unique=False)
    op.create_table('dealer_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['geo_cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['province_id'], ['geo_provinces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dealer_req_status', 'dealer_requests', ['status'], unique=False)
    op.create_index('ix_dealer_req_user', 'dealer_requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_dealer_requests_id'), 'dealer_requests', ['id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('email_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'notification_type', name='uq_notif_pref_user_type')
    )
    op.create_index('ix_notif_pref_user', 'notification_preferences', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('channel', sa.String(length=20), server_default='IN_APP', nullable=False),
    sa.Column('reference_type', sa.String(length=100), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_ref', 'notifications', ['reference_type', 'reference_id'], unique=False)
    op.create_index('ix_notification_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_notification_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('delivery_method', sa.String(), nullable=True),
    sa.Column('delivery_status', sa.String(), nullable=True),
    sa.Column('pickup_dealer_id', sa.Integer(), nullable=True),
    sa.Column('delivery_code_hash', sa.String(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipping_province', sa.String(), nullable=True),
    sa.Column('shipping_city', sa.String(), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('shipping_postal_code', sa.String(), nullable=True),
    sa.Column('shipping_cost', sa.BigInteger(), nullable=False),
    sa.Column('insurance_cost', sa.BigInteger(), nullable=False),
    sa.Column('postal_tracking_code', sa.String(), nullable=True),
    sa.Column('promo_choice', sa.String(), nullable=True),
    sa.Column('promo_amount', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('cashback_settled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('coupon_code', sa.String(), nullable=True),
    sa.Column('is_gift', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('cancellation_reason', sa.String(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('payment_ref', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_asset_code', sa.String(length=10), nullable=True),
    sa.Column('gold_total_mg', sa.BigInteger(), nullable=True),
    sa.Column('delivery_otp_hash', sa.String(), nullable=True),
    sa.Column('delivery_otp_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pickup_dealer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('position_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metal_type', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('amount_mg', sa.BigInteger(), nullable=False),
    sa.Column('balance_after_mg', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('metal_price_per_gram', sa.BigInteger(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('involved_user_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['involved_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_pos_ledger_metal_created', 'position_ledger', ['metal_type', 'created_at'], unique=False)
    op.create_index('ix_pos_ledger_source', 'position_ledger', ['source_type', 'source_id'], unique=False)
    op.create_table('product_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('sender_type', sa.String(), nullable=False),
    sa.Column('sender_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['product_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comment_parent', 'product_comments', ['parent_id'], unique=False)
    op.create_index('ix_comment_product', 'product_comments', ['product_id'], unique=False)
    op.create_table('reconciliation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('initiated_by', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_expected', sa.Integer(), nullable=True),
    sa.Column('total_scanned', sa.Integer(), nullable=True),
    sa.Column('total_matched', sa.Integer(), nullable=True),
    sa.Column('total_missing', sa.Integer(), nullable=True),
    sa.Column('total_unexpected', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_sessions_dealer_id'), 'reconciliation_sessions', ['dealer_id'], unique=False)
    op.create_table('sub_dealer_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_dealer_id', sa.Integer(), nullable=False),
    sa.Column('child_dealer_id', sa.Integer(), nullable=False),
    sa.Column('commission_split_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.CheckConstraint('commission_split_percent >= 0 AND commission_split_percent <= 100', name='ck_commission_split_range'),
    sa.CheckConstraint('parent_dealer_id != child_dealer_id', name='ck_no_self_reference'),
    sa.ForeignKeyConstraint(['child_dealer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_dealer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_dealer_id', 'child_dealer_id', name='uq_sub_dealer_relation')
    )
    op.create_index(op.f('ix_sub_dealer_relations_child_dealer_id'), 'sub_dealer_relations', ['child_dealer_id'], unique=False)
    op.create_index(op.f('ix_sub_dealer_relations_parent_dealer_id'), 'sub_dealer_relations', ['parent_dealer_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('sender_type', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_status_sender', 'tickets', ['status', 'sender_type'], unique=False)
    op.create_index('ix_ticket_user', 'tickets', ['user_id'], unique=False)
    op.create_table('wallet_topups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_irr', sa.BigInteger(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('ref_number', sa.String(), nullable=True),
    sa.Column('gateway', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id')
    )
    op.create_index(op.f('ix_wallet_topups_user_id'), 'wallet_topups', ['user_id'], unique=False)
    op.create_table('withdrawal_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_irr', sa.BigInteger(), nullable=False),
    sa.Column('shaba_number', sa.String(), nullable=False),
    sa.Column('account_holder', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('admin_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawal_requests_user_id'), 'withdrawal_requests', ['user_id'], unique=False)
    op.create_table('article_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_article_comment_approved', 'article_comments', ['article_id', 'is_approved'], unique=False)
    op.create_index('ix_article_comment_article', 'article_comments', ['article_id'], unique=False)
    op.create_table('article_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_images_article_id'), 'article_images', ['article_id'], unique=False)
    op.create_table('article_tag_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['article_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'tag_id', name='uq_article_tag_link')
    )
    op.create_index(op.f('ix_article_tag_links_article_id'), 'article_tag_links', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_tag_links_tag_id'), 'article_tag_links', ['tag_id'], unique=False)
    op.create_table('bar_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('bar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bar_images_bar_id'), 'bar_images', ['bar_id'], unique=False)
    op.create_table('bar_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bar_id', sa.Integer(), nullable=False),
    sa.Column('from_customer_id', sa.Integer(), nullable=False),
    sa.Column('to_mobile', sa.String(length=11), nullable=False),
    sa.Column('otp_hash', sa.String(), nullable=True),
    sa.Column('otp_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bar_transfers_bar_id'), 'bar_transfers', ['bar_id'], unique=False)
    op.create_index(op.f('ix_bar_transfers_from_customer_id'), 'bar_transfers', ['from_customer_id'], unique=False)
    op.create_table('buyback_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('bar_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_mobile', sa.String(length=15), nullable=True),
    sa.Column('seller_national_id', sa.String(), nullable=True),
    sa.Column('seller_user_id', sa.Integer(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('buyback_price', sa.BigInteger(), nullable=False),
    sa.Column('wage_refund_amount', sa.BigInteger(), nullable=False),
    sa.Column('wage_refund_customer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('otp_hash', sa.String(), nullable=True),
    sa.Column('otp_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dealer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyback_requests_bar_id'), 'buyback_requests', ['bar_id'], unique=False)
    op.create_index(op.f('ix_buyback_requests_dealer_id'), 'buyback_requests', ['dealer_id'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('gift_box_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('quantity >= 1', name='ck_cart_qty'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gift_box_id'], ['gift_boxes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'product_id', name='uq_cart_product')
    )
    op.create_table('comment_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['product_comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['product_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', name='uq_comment_like')
    )
    op.create_table('coupon_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coupon_category_unique', 'coupon_categories', ['coupon_id', 'category_id'], unique=True)
    op.create_table('coupon_mobiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coupon_mobile_unique', 'coupon_mobiles', ['coupon_id', 'mobile'], unique=True)
    op.create_table('coupon_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('discount_amount', sa.BigInteger(), nullable=False),
    sa.Column('cashback_settled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_coupon_user', 'coupon_usages', ['coupon_id', 'user_id'], unique=False)
    op.create_table('custodial_delivery_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('bar_id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('otp_hash', sa.String(), nullable=True),
    sa.Column('otp_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.String(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dealer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custodial_delivery_requests_bar_id'), 'custodial_delivery_requests', ['bar_id'], unique=False)
    op.create_index(op.f('ix_custodial_delivery_requests_customer_id'), 'custodial_delivery_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_custodial_delivery_requests_dealer_id'), 'custodial_delivery_requests', ['dealer_id'], unique=False)
    op.create_table('dealer_location_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bar_id', sa.Integer(), nullable=False),
    sa.Column('from_dealer_id', sa.Integer(), nullable=True),
    sa.Column('to_dealer_id', sa.Integer(), nullable=True),
    sa.Column('transferred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('transferred_by', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('transfer_type', sa.String(length=30), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_dealer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_dealer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealer_location_transfers_bar_id'), 'dealer_location_transfers', ['bar_id'], unique=False)
    op.create_index(op.f('ix_dealer_location_transfers_from_dealer_id'), 'dealer_location_transfers', ['from_dealer_id'], unique=False)
    op.create_index(op.f('ix_dealer_location_transfers_to_dealer_id'), 'dealer_location_transfers', ['to_dealer_id'], unique=False)
    op.create_table('dealer_request_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_request_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dealer_request_id'], ['dealer_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dealer_req_attach_req', 'dealer_request_attachments', ['dealer_request_id'], unique=False)
    op.create_index(op.f('ix_dealer_request_attachments_id'), 'dealer_request_attachments', ['id'], unique=False)
    op.create_table('dealer_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('bar_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_mobile', sa.String(length=15), nullable=True),
    sa.Column('customer_national_id', sa.String(), nullable=True),
    sa.Column('sale_price', sa.BigInteger(), nullable=False),
    sa.Column('applied_metal_price', sa.BigInteger(), nullable=True),
    sa.Column('commission_amount', sa.BigInteger(), nullable=False),
    sa.Column('metal_profit_mg', sa.BigInteger(), nullable=False),
    sa.Column('metal_type', sa.String(length=20), nullable=False),
    sa.Column('discount_wage_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_dealer_id', sa.Integer(), nullable=True),
    sa.Column('parent_commission_mg', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dealer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_dealer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealer_sales_bar_id'), 'dealer_sales', ['bar_id'], unique=False)
    op.create_index(op.f('ix_dealer_sales_dealer_id'), 'dealer_sales', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_dealer_sales_parent_dealer_id'), 'dealer_sales', ['parent_dealer_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('txn_type', sa.String(), nullable=False),
    sa.Column('delta_balance', sa.BigInteger(), nullable=False),
    sa.Column('delta_locked', sa.BigInteger(), nullable=False),
    sa.Column('delta_credit', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('locked_after', sa.BigInteger(), nullable=False),
    sa.Column('credit_after', sa.BigInteger(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_ledger_account_created', 'ledger_entries', ['account_id', 'created_at'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('bar_id', sa.Integer(), nullable=True),
    sa.Column('applied_metal_price', sa.BigInteger(), nullable=False),
    sa.Column('applied_unit_price', sa.BigInteger(), nullable=False),
    sa.Column('applied_weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('applied_purity', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('applied_wage_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('applied_tax_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('final_gold_amount', sa.BigInteger(), nullable=False),
    sa.Column('final_wage_amount', sa.BigInteger(), nullable=False),
    sa.Column('final_tax_amount', sa.BigInteger(), nullable=False),
    sa.Column('line_total', sa.BigInteger(), nullable=False),
    sa.Column('gold_cost_mg', sa.BigInteger(), nullable=True),
    sa.Column('applied_dealer_wage_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gift_box_id', sa.Integer(), nullable=True),
    sa.Column('applied_gift_box_price', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('line_total >= 0', name='ck_order_item_line_total_nonneg'),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gift_box_id'], ['gift_boxes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_bar_id'), 'order_items', ['bar_id'], unique=False)
    op.create_index(op.f('ix_order_items_gift_box_id'), 'order_items', ['gift_box_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_table('order_status_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=False),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_logs_order_id'), 'order_status_logs', ['order_id'], unique=False)
    op.create_table('ownership_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bar_id', sa.Integer(), nullable=False),
    sa.Column('previous_owner_id', sa.Integer(), nullable=True),
    sa.Column('new_owner_id', sa.Integer(), nullable=True),
    sa.Column('transfer_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['new_owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ownership_history_bar_id'), 'ownership_history', ['bar_id'], unique=False)
    op.create_table('reconciliation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('bar_id', sa.Integer(), nullable=True),
    sa.Column('serial_code', sa.String(length=12), nullable=False),
    sa.Column('item_status', sa.String(length=20), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expected_status', sa.String(), nullable=True),
    sa.Column('expected_product', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['reconciliation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_items_bar_id'), 'reconciliation_items', ['bar_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_items_session_id'), 'reconciliation_items', ['session_id'], unique=False)
    op.create_table('ticket_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.String(), nullable=False),
    sa.Column('sender_name', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('is_initial', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_msg_ticket', 'ticket_messages', ['ticket_id'], unique=False)
    op.create_table('rasis_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('receipt_no', sa.BigInteger(), nullable=True),
    sa.Column('record_version', sa.BigInteger(), nullable=True),
    sa.Column('factor_tarikh', sa.String(), nullable=True),
    sa.Column('total_amount', sa.BigInteger(), nullable=True),
    sa.Column('pay_card', sa.BigInteger(), nullable=True),
    sa.Column('pay_cash', sa.BigInteger(), nullable=True),
    sa.Column('payer_mobile', sa.String(length=15), nullable=True),
    sa.Column('payer_name', sa.String(), nullable=True),
    sa.Column('product_cbrc', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('item_price', sa.BigInteger(), nullable=True),
    sa.Column('item_total', sa.BigInteger(), nullable=True),
    sa.Column('bar_id', sa.Integer(), nullable=True),
    sa.Column('dealer_sale_id', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dealer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dealer_sale_id'], ['dealer_sales.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rasis_receipts_dealer_id'), 'rasis_receipts', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_rasis_receipts_product_cbrc'), 'rasis_receipts', ['product_cbrc'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('admin_reply_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_item_id')
    )
    op.create_index('ix_review_product', 'reviews', ['product_id'], unique=False)
    op.create_index('ix_review_user', 'reviews', ['user_id'], unique=False)
    op.create_table('ticket_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['ticket_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_attachment_message', 'ticket_attachments', ['message_id'], unique=False)
    op.create_table('review_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_irr', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('gateway', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ref_number', sa.String(length=100), nullable=True),
    sa.Column('track_id', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_payment_links_token'), 'payment_links', ['token'], unique=True)
    op.create_index(op.f('ix_payment_links_user_id'), 'payment_links', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_links_user_id'), table_name='payment_links')
    op.drop_index(op.f('ix_payment_links_token'), table_name='payment_links')
    op.drop_table('payment_links')
    op.drop_table('review_images')
    op.drop_index('ix_ticket_attachment_message', table_name='ticket_attachments')
    op.drop_table('ticket_attachments')
    op.drop_index('ix_review_user', table_name='reviews')
    op.drop_index('ix_review_product', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_rasis_receipts_product_cbrc'), table_name='rasis_receipts')
    op.drop_index(op.f('ix_rasis_receipts_dealer_id'), table_name='rasis_receipts')
    op.drop_table('rasis_receipts')
    op.drop_index('ix_ticket_msg_ticket', table_name='ticket_messages')
    op.drop_table('ticket_messages')
    op.drop_index(op.f('ix_reconciliation_items_session_id'), table_name='reconciliation_items')
    op.drop_index(op.f('ix_reconciliation_items_bar_id'), table_name='reconciliation_items')
    op.drop_table('reconciliation_items')
    op.drop_index(op.f('ix_ownership_history_bar_id'), table_name='ownership_history')
    op.drop_table('ownership_history')
    op.drop_index(op.f('ix_order_status_logs_order_id'), table_name='order_status_logs')
    op.drop_table('order_status_logs')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_gift_box_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_bar_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_ledger_account_created', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_dealer_sales_parent_dealer_id'), table_name='dealer_sales')
    op.drop_index(op.f('ix_dealer_sales_dealer_id'), table_name='dealer_sales')
    op.drop_index(op.f('ix_dealer_sales_bar_id'), table_name='dealer_sales')
    op.drop_table('dealer_sales')
    op.drop_index(op.f('ix_dealer_request_attachments_id'), table_name='dealer_request_attachments')
    op.drop_index('ix_dealer_req_attach_req', table_name='dealer_request_attachments')
    op.drop_table('dealer_request_attachments')
    op.drop_index(op.f('ix_dealer_location_transfers_to_dealer_id'), table_name='dealer_location_transfers')
    op.drop_index(op.f('ix_dealer_location_transfers_from_dealer_id'), table_name='dealer_location_transfers')
    op.drop_index(op.f('ix_dealer_location_transfers_bar_id'), table_name='dealer_location_transfers')
    op.drop_table('dealer_location_transfers')
    op.drop_index(op.f('ix_custodial_delivery_requests_dealer_id'), table_name='custodial_delivery_requests')
    op.drop_index(op.f('ix_custodial_delivery_requests_customer_id'), table_name='custodial_delivery_requests')
    op.drop_index(op.f('ix_custodial_delivery_requests_bar_id'), table_name='custodial_delivery_requests')
    op.drop_table('custodial_delivery_requests')
    op.drop_index('ix_usage_coupon_user', table_name='coupon_usages')
    op.drop_table('coupon_usages')
    op.drop_index('ix_coupon_mobile_unique', table_name='coupon_mobiles')
    op.drop_table('coupon_mobiles')
    op.drop_index('ix_coupon_category_unique', table_name='coupon_categories')
    op.drop_table('coupon_categories')
    op.drop_table('comment_likes')
    op.drop_table('comment_images')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_buyback_requests_dealer_id'), table_name='buyback_requests')
    op.drop_index(op.f('ix_buyback_requests_bar_id'), table_name='buyback_requests')
    op.drop_table('buyback_requests')
    op.drop_index(op.f('ix_bar_transfers_from_customer_id'), table_name='bar_transfers')
    op.drop_index(op.f('ix_bar_transfers_bar_id'), table_name='bar_transfers')
    op.drop_table('bar_transfers')
    op.drop_index(op.f('ix_bar_images_bar_id'), table_name='bar_images')
    op.drop_table('bar_images')
    op.drop_index(op.f('ix_article_tag_links_tag_id'), table_name='article_tag_links')
    op.drop_index(op.f('ix_article_tag_links_article_id'), table_name='article_tag_links')
    op.drop_table('article_tag_links')
    op.drop_index(op.f('ix_article_images_article_id'), table_name='article_images')
    op.drop_table('article_images')
    op.drop_index('ix_article_comment_article', table_name='article_comments')
    op.drop_index('ix_article_comment_approved', table_name='article_comments')
    op.drop_table('article_comments')
    op.drop_index(op.f('ix_withdrawal_requests_user_id'), table_name='withdrawal_requests')
    op.drop_table('withdrawal_requests')
    op.drop_index(op.f('ix_wallet_topups_user_id'), table_name='wallet_topups')
    op.drop_table('wallet_topups')
    op.drop_index('ix_ticket_user', table_name='tickets')
    op.drop_index('ix_ticket_status_sender', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_sub_dealer_relations_parent_dealer_id'), table_name='sub_dealer_relations')
    op.drop_index(op.f('ix_sub_dealer_relations_child_dealer_id'), table_name='sub_dealer_relations')
    op.drop_table('sub_dealer_relations')
    op.drop_index(op.f('ix_reconciliation_sessions_dealer_id'), table_name='reconciliation_sessions')
    op.drop_table('reconciliation_sessions')
    op.drop_index('ix_comment_product', table_name='product_comments')
    op.drop_index('ix_comment_parent', table_name='product_comments')
    op.drop_table('product_comments')
    op.drop_index('ix_pos_ledger_source', table_name='position_ledger')
    op.drop_index('ix_pos_ledger_metal_created', table_name='position_ledger')
    op.drop_table('position_ledger')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_notification_user_unread', table_name='notifications')
    op.drop_index('ix_notification_user_created', table_name='notifications')
    op.drop_index('ix_notification_ref', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_notif_pref_user', table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_dealer_requests_id'), table_name='dealer_requests')
    op.drop_index('ix_dealer_req_user', table_name='dealer_requests')
    op.drop_index('ix_dealer_req_status', table_name='dealer_requests')
    op.drop_table('dealer_requests')
    op.drop_index(op.f('ix_customer_addresses_user_id'), table_name='customer_addresses')
    op.drop_index(op.f('ix_customer_addresses_province_id'), table_name='customer_addresses')
    op.drop_index(op.f('ix_customer_addresses_district_id'), table_name='customer_addresses')
    op.drop_index(op.f('ix_customer_addresses_city_id'), table_name='customer_addresses')
    op.drop_table('customer_addresses')
    op.drop_index(op.f('ix_coupons_scope_product_id'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_referrer_user_id'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_index('ix_coupon_code_status', table_name='coupons')
    op.drop_table('coupons')
    op.drop_table('carts')
    op.drop_index(op.f('ix_bars_serial_code'), table_name='bars')
    op.drop_index(op.f('ix_bars_product_id'), table_name='bars')
    op.drop_index(op.f('ix_bars_id'), table_name='bars')
    op.drop_index(op.f('ix_bars_dealer_id'), table_name='bars')
    op.drop_index(op.f('ix_bars_customer_id'), table_name='bars')
    op.drop_index(op.f('ix_bars_claim_code'), table_name='bars')
    op.drop_index(op.f('ix_bars_batch_id'), table_name='bars')
    op.drop_table('bars')
    op.drop_index(op.f('ix_articles_category_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_author_id'), table_name='articles')
    op.drop_index('ix_article_status_published', table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index('ix_account_user_asset', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_tier_id'), table_name='users')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_province_id'), table_name='users')
    op.drop_index(op.f('ix_users_national_id'), table_name='users')
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_index(op.f('ix_users_is_dealer'), table_name='users')
    op.drop_index(op.f('ix_users_is_admin'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_district_id'), table_name='users')
    op.drop_index('ix_users_created', table_name='users')
    op.drop_index(op.f('ix_users_city_id'), table_name='users')
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_product_tier_wages_tier_id'), table_name='product_tier_wages')
    op.drop_index(op.f('ix_product_tier_wages_product_id'), table_name='product_tier_wages')
    op.drop_table('product_tier_wages')
    op.drop_index(op.f('ix_product_package_links_product_id'), table_name='product_package_links')
    op.drop_index(op.f('ix_product_package_links_package_type_id'), table_name='product_package_links')
    op.drop_table('product_package_links')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_product_category_links_product_id'), table_name='product_category_links')
    op.drop_index(op.f('ix_product_category_links_category_id'), table_name='product_category_links')
    op.drop_table('product_category_links')
    op.drop_index(op.f('ix_geo_districts_city_id'), table_name='geo_districts')
    op.drop_table('geo_districts')
    op.drop_index(op.f('ix_products_package_type_id'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_package_type_images_package_id'), table_name='package_type_images')
    op.drop_table('package_type_images')
    op.drop_index(op.f('ix_gift_box_images_gift_box_id'), table_name='gift_box_images')
    op.drop_table('gift_box_images')
    op.drop_index(op.f('ix_geo_cities_province_id'), table_name='geo_cities')
    op.drop_table('geo_cities')
    op.drop_index(op.f('ix_batch_images_batch_id'), table_name='batch_images')
    op.drop_table('batch_images')
    op.drop_table('testimonials')
    op.drop_index(op.f('ix_system_users_mobile'), table_name='system_users')
    op.drop_table('system_users')
    op.drop_table('system_settings')
    op.drop_index('ix_reqlog_user_type', table_name='request_logs')
    op.drop_index('ix_reqlog_path', table_name='request_logs')
    op.drop_index('ix_reqlog_method', table_name='request_logs')
    op.drop_index('ix_reqlog_ip', table_name='request_logs')
    op.drop_index('ix_reqlog_created', table_name='request_logs')
    op.drop_table('request_logs')
    op.drop_table('product_categories')
    op.drop_table('package_types')
    op.drop_table('metal_positions')
    op.drop_table('gift_boxes')
    op.drop_table('geo_provinces')
    op.drop_table('dealer_tiers')
    op.drop_table('batches')
    op.drop_table('assets')
    op.drop_table('article_tags')
    op.drop_table('article_categories')
    # ### end Alembic commands ###
