"""add delivery system

Revision ID: 30ea9f74485d
Revises: a016f63eff49
Create Date: 2026-02-09 20:36:47.227523
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ea9f74485d'
down_revision: Union[str, None] = 'a016f63eff49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('province', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('is_postal_hub', sa.Boolean(), nullable=False))
    op.add_column('orders', sa.Column('delivery_method', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_status', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('pickup_location_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('delivery_code_hash', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('shipping_province', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_city', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_address', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('shipping_postal_code', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_cost', sa.BigInteger(), nullable=False))
    op.add_column('orders', sa.Column('insurance_cost', sa.BigInteger(), nullable=False))
    op.add_column('orders', sa.Column('postal_tracking_code', sa.String(), nullable=True))
    op.create_foreign_key(None, 'orders', 'locations', ['pickup_location_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'postal_tracking_code')
    op.drop_column('orders', 'insurance_cost')
    op.drop_column('orders', 'shipping_cost')
    op.drop_column('orders', 'shipping_postal_code')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'shipping_city')
    op.drop_column('orders', 'shipping_province')
    op.drop_column('orders', 'delivered_at')
    op.drop_column('orders', 'delivery_code_hash')
    op.drop_column('orders', 'pickup_location_id')
    op.drop_column('orders', 'delivery_status')
    op.drop_column('orders', 'delivery_method')
    op.drop_column('locations', 'is_postal_hub')
    op.drop_column('locations', 'province')
    # ### end Alembic commands ###
