"""add cart and order models

Revision ID: 748cc5d523e6
Revises: b9694680e317
Create Date: 2026-02-09 07:38:46.924615
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '748cc5d523e6'
down_revision: Union[str, None] = 'b9694680e317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('promo_choice', sa.String(), nullable=True),
    sa.Column('promo_amount', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('cashback_settled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('coupon_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 1', name='ck_cart_qty'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'product_id', name='uq_cart_product')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('bar_id', sa.Integer(), nullable=True),
    sa.Column('applied_gold_price', sa.BigInteger(), nullable=False),
    sa.Column('applied_unit_price', sa.BigInteger(), nullable=False),
    sa.Column('applied_weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('applied_purity', sa.Integer(), nullable=False),
    sa.Column('applied_profit_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('applied_commission_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('applied_tax_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('final_gold_amount', sa.BigInteger(), nullable=False),
    sa.Column('final_wage_amount', sa.BigInteger(), nullable=False),
    sa.Column('final_profit_amount', sa.BigInteger(), nullable=False),
    sa.Column('final_commission_amount', sa.BigInteger(), nullable=False),
    sa.Column('final_stone_amount', sa.BigInteger(), nullable=False),
    sa.Column('final_accessory_amount', sa.BigInteger(), nullable=False),
    sa.Column('final_tax_amount', sa.BigInteger(), nullable=False),
    sa.Column('final_exempt_amount', sa.BigInteger(), nullable=False),
    sa.Column('taxable_services_base', sa.BigInteger(), nullable=False),
    sa.Column('taxable_goods_base', sa.BigInteger(), nullable=False),
    sa.Column('line_total', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('carts')
    # ### end Alembic commands ###
