"""
TalaMala v4 - Migration Script: Import Old Bar Serials
=======================================================
Imports 645 bar serial codes + 2 Raw bars from the old system into talamala_v4
so they appear in the authenticity verification page (/verify/check).

Usage on server:
    cd /path/to/talamala_v4
    python scripts/migrate_old_bars.py

Safe to re-run: skips bars whose serial_code already exists.
"""

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy import text
from config.database import engine


# ============================================================
# Product mapping: ALL old gold bars -> "شمش طلا طلاملا" series
# ============================================================
PRODUCT_MAP = {
    1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11,
    16: 1, 17: 2, 18: 3, 19: 4, 20: 5, 21: 6, 22: 7, 23: 8, 24: 11, 25: 10, 26: 9,
    27: 23,
}

# Format: (serial_code, status, old_product_id, customer_mobile_or_None)
OLD_BARS = [
("69K5NX6C", "Assigned", 1, None),
("368P7LWT", "Assigned", 1, None),
("VXMYX5XE", "Assigned", 1, None),
("5C453PXR", "Assigned", 1, None),
("BM59JUYY", "Assigned", 1, None),
("9GMX3XVK", "Assigned", 1, None),
("68GFDFFE", "Assigned", 1, None),
("K4PLPH7W", "Assigned", 1, None),
("7XFML3RB", "Assigned", 1, None),
("J4SXM65P", "Assigned", 1, None),
("4FAG3AWC", "Assigned", 1, None),
("TE5HRAFY", "Assigned", 1, None),
("CZL6B8N5", "Assigned", 1, None),
("LBPWWPJ3", "Assigned", 1, None),
("HHMHAPNF", "Assigned", 1, None),
("5CMJ84QG", "Assigned", 1, None),
("NUPJ4CG5", "Assigned", 1, None),
("TNJDXJSP", "Assigned", 1, None),
("V4XXKR6H", "Assigned", 1, None),
("9WHBP4TD", "Assigned", 1, None),
("Z82A2LUF", "Assigned", 1, None),
("H7EWE354", "Assigned", 1, None),
("7RBVRWA5", "Assigned", 1, None),
("SGZWEEAZ", "Assigned", 1, None),
("C3GN6Y38", "Assigned", 1, None),
("GCR5FUUM", "Assigned", 1, None),
("DNK5JE5G", "Assigned", 1, None),
("F9XF3YZX", "Assigned", 1, None),
("347FHTSK", "Assigned", 1, None),
("8XYESXT2", "Assigned", 1, None),
("JC7PNX5A", "Assigned", 1, None),
("FKW9SR7Y", "Assigned", 1, None),
("5T3VJFQU", "Assigned", 1, None),
("BV4NU8YD", "Assigned", 1, None),
("GFY25PXF", "Assigned", 1, None),
("QGZUEWVC", "Assigned", 1, None),
("KZZ6Q325", "Assigned", 1, None),
("TF33H8GS", "Assigned", 1, None),
("PK84AMSD", "Assigned", 1, None),
("TB4MKJRG", "Assigned", 1, None),
("W5EB8VF8", "Assigned", 1, None),
("5DYVP9AM", "Assigned", 1, None),
("S5P8YQKW", "Assigned", 1, None),
("FZ7UP6E6", "Assigned", 1, None),
("CP3XE648", "Assigned", 1, None),
("WEB3F7EE", "Assigned", 1, None),
("S5VN5WGP", "Assigned", 1, None),
("5EE3YCJF", "Assigned", 1, None),
("QZE33WHA", "Assigned", 1, None),
("FAWTSK65", "Assigned", 1, None),
("VLTQCR88", "Assigned", 1, None),
("6Y4Q9ZX7", "Assigned", 1, None),
("V9E3FWXJ", "Assigned", 1, None),
("WEEEEFCR", "Assigned", 1, None),
("679MHZSJ", "Assigned", 1, None),
("HDYLNW4R", "Assigned", 1, None),
("22HY3PDF", "Assigned", 1, None),
("8FRAG6M3", "Assigned", 1, None),
("8AFKPZXZ", "Assigned", 1, None),
("SUFFVR2G", "Assigned", 1, None),
("623K98SB", "Assigned", 1, None),
("UPCA47XR", "Assigned", 1, None),
("94LEXNLL", "Sold", 1, "09121058447"),
("X5FUFPM9", "Assigned", 1, None),
("HKESZ3BQ", "Assigned", 1, None),
("26RPQ59V", "Assigned", 1, None),
("4BFH9HH4", "Assigned", 1, None),
("39ZBNUGC", "Assigned", 1, None),
("78EYLTFF", "Assigned", 1, None),
("P3YH6EZV", "Assigned", 1, None),
("D5KBKW97", "Assigned", 1, None),
("CFHCN5NK", "Assigned", 1, None),
("PCN7869A", "Assigned", 1, None),
("VW6PBD79", "Assigned", 1, None),
("L5TJEY5B", "Assigned", 1, None),
("LUDJUUNT", "Assigned", 1, None),
("ELZPXLVM", "Assigned", 1, None),
("SYGKL6XA", "Assigned", 1, None),
("GEAUY6VX", "Assigned", 1, None),
("8MK3EYRZ", "Assigned", 1, None),
("8486XF2G", "Assigned", 1, None),
("23EEHEX7", "Assigned", 1, None),
("SG5B8RLJ", "Assigned", 1, None),
("UBR8Z2SX", "Assigned", 1, None),
("GLBCYEFA", "Assigned", 1, None),
("DSECK6CF", "Assigned", 1, None),
("PRJVM853", "Assigned", 1, None),
("77J7ZS6J", "Assigned", 1, None),
("VJVPB9YA", "Assigned", 1, None),
("YDWTRHW4", "Assigned", 1, None),
("B3EHW6UU", "Assigned", 1, None),
("35KRF79M", "Assigned", 1, None),
("WDJR5SBP", "Assigned", 1, None),
("TRSYTKLJ", "Assigned", 1, None),
("H7BGUEEX", "Assigned", 1, None),
("XTGXZW5J", "Assigned", 1, None),
("F4KVZP7T", "Assigned", 1, None),
("R7HZDSQN", "Assigned", 1, None),
("VP93GYBW", "Assigned", 1, None),
("CXVAUWRX", "Assigned", 1, None),
("QX6CZ2LG", "Assigned", 1, None),
("MQA2GEL8", "Assigned", 1, None),
("MFK23A3X", "Assigned", 1, None),
("9XFBRG73", "Assigned", 1, None),
("UJ2HN9ZW", "Assigned", 1, None),
("5JJRG78X", "Assigned", 1, None),
("Q29RWRQC", "Assigned", 1, None),
("Q6KATNYG", "Assigned", 1, None),
("8X9Q9EBB", "Assigned", 1, None),
("NZZFCUKU", "Assigned", 1, None),
("UWVV8NBU", "Assigned", 1, None),
("CT6FZYMY", "Assigned", 1, None),
("GXJ9W5W8", "Assigned", 1, None),
("BKYHGTKV", "Assigned", 1, None),
("4L3J35BM", "Assigned", 1, None),
("NH5LDD8S", "Assigned", 1, None),
("E6YG6TTD", "Assigned", 1, None),
("THWQBTMW", "Assigned", 1, None),
("JNFGTPHF", "Assigned", 1, None),
("WFPT5JY5", "Assigned", 1, None),
("SWSRX2LN", "Assigned", 1, None),
("89T6HUTT", "Assigned", 1, None),
("QZWC2Z6R", "Assigned", 1, None),
("9J2EF6GB", "Assigned", 1, None),
("W6QTP93L", "Assigned", 1, None),
("R5V8CA8P", "Assigned", 2, None),
("BYFL9CSV", "Assigned", 2, None),
("DYPAELB6", "Assigned", 2, None),
("VUSF9TTZ", "Assigned", 2, None),
("RNN3TDZG", "Assigned", 2, None),
("HWK6QELS", "Assigned", 2, None),
("HHXXND2G", "Assigned", 2, None),
("65X5Y45J", "Assigned", 2, None),
("G6MU4KEQ", "Assigned", 2, None),
("G48PL2QZ", "Assigned", 2, None),
("QTCDU6FH", "Assigned", 2, None),
("UBHPUWK9", "Assigned", 2, None),
("J43S2EY8", "Assigned", 2, None),
("TMLQY8ED", "Assigned", 2, None),
("CB6KMGH3", "Assigned", 2, None),
("TK6GJBKP", "Assigned", 2, None),
("JMVA54X8", "Assigned", 2, None),
("ZUK6N8AA", "Assigned", 2, None),
("2B2B6M3E", "Assigned", 2, None),
("LVWMKVE2", "Assigned", 2, None),
("CBJKQL7W", "Assigned", 2, None),
("D4CMFYU3", "Assigned", 2, None),
("LFSDKSGQ", "Assigned", 2, None),
("FXP9GJEL", "Assigned", 2, None),
("EUUFX9FG", "Assigned", 2, None),
("LMT47SDN", "Assigned", 2, None),
("VVDZDQM8", "Assigned", 2, None),
("RWGE559P", "Assigned", 2, None),
("Z6Y9U4T7", "Assigned", 2, None),
("38GBDT58", "Assigned", 2, None),
("DJML34MB", "Assigned", 2, None),
("GZBRRQN4", "Assigned", 2, None),
("9HQXENR3", "Assigned", 2, None),
("9CMHK6N8", "Assigned", 2, None),
("XECL7M9M", "Assigned", 2, None),
("25R8THY7", "Assigned", 2, None),
("N88UD9P9", "Assigned", 2, None),
("PMD6FSGZ", "Assigned", 2, None),
("MUH8N3VK", "Assigned", 2, None),
("MAA2VGYU", "Assigned", 2, None),
("XNVPCPUA", "Assigned", 2, None),
("R3BSVFWG", "Assigned", 2, None),
("NT6JYQS3", "Assigned", 2, None),
("LYYCERF3", "Assigned", 2, None),
("58LDLZEV", "Assigned", 2, None),
("VTBP53DA", "Assigned", 2, None),
("R6ZEMKKT", "Assigned", 2, None),
("PHDTXSZQ", "Assigned", 2, None),
("E9NAZH2K", "Assigned", 2, None),
("42EKPV3Z", "Assigned", 2, None),
("DCHA63ZP", "Assigned", 2, None),
("J3RM82KH", "Assigned", 2, None),
("DL4S9FPK", "Assigned", 2, None),
("BYLK9KSY", "Assigned", 2, None),
("L2CFXT7Z", "Assigned", 2, None),
("F45QFWWY", "Assigned", 2, None),
("ZDU5WX9J", "Assigned", 2, None),
("C6H3DLHP", "Assigned", 2, None),
("T4UNSUJ8", "Assigned", 2, None),
("SS9FB5QT", "Assigned", 2, None),
("XBQRYMLA", "Assigned", 2, None),
("PYBX6T7V", "Assigned", 2, None),
("47LZW9EW", "Assigned", 2, None),
("F2JF6ZPR", "Assigned", 2, None),
("U7CCFYV8", "Assigned", 2, None),
("HLMJWU25", "Assigned", 2, None),
("2KQSNMC6", "Assigned", 2, None),
("TSDFUJAG", "Assigned", 2, None),
("SHQA6RRT", "Assigned", 2, None),
("J5UC8AEM", "Assigned", 2, None),
("UW3LHX4H", "Assigned", 2, None),
("99YBCZCQ", "Assigned", 2, None),
("55LSBJVQ", "Assigned", 2, None),
("8W4LTAPN", "Assigned", 2, None),
("3A7AFCUM", "Assigned", 2, None),
("5CMRN3XW", "Assigned", 2, None),
("Z87UG7BC", "Assigned", 2, None),
("Q7Y997NB", "Assigned", 3, None),
("5R5PPKQX", "Assigned", 3, None),
("JUDPWQXZ", "Assigned", 3, None),
("DG2FG6GW", "Assigned", 3, None),
("4E4D3WFB", "Assigned", 3, None),
("64U8V6BS", "Assigned", 3, None),
("7DD78H27", "Assigned", 3, None),
("NBVSYP46", "Assigned", 3, None),
("WGE8YGJG", "Assigned", 3, None),
("NH9BSCN8", "Assigned", 3, None),
("MVJXZS3N", "Assigned", 3, None),
("ZVTCG7HT", "Assigned", 3, None),
("UC89PVUC", "Assigned", 3, None),
("R5HCHEZ5", "Assigned", 3, None),
("BVXMFS32", "Assigned", 3, None),
("AWB2S25V", "Assigned", 3, None),
("KRCEQX8N", "Assigned", 3, None),
("ACB4LW3C", "Assigned", 3, None),
("TTPVSKK2", "Assigned", 3, None),
("WQDXESTN", "Assigned", 3, None),
("GEQ6SS46", "Assigned", 3, None),
("BYYUKRQL", "Assigned", 3, None),
("JXG49VXP", "Assigned", 3, None),
("5PFMD44S", "Assigned", 3, None),
("494NCXUP", "Assigned", 3, None),
("DD39AHDW", "Assigned", 3, None),
("AKYHQ6DA", "Assigned", 3, None),
("SF62ZD4F", "Assigned", 3, None),
("32ESY59J", "Assigned", 3, None),
("NB9QM6K8", "Assigned", 3, None),
("DLZY3GGK", "Assigned", 3, None),
("97KEDZZ5", "Assigned", 3, None),
("P33RMGHU", "Assigned", 3, None),
("6REL2TRU", "Assigned", 3, None),
("2B4AHQUT", "Assigned", 3, None),
("LXJVCJMW", "Assigned", 3, None),
("GF9CPS9E", "Assigned", 3, None),
("3BGUHQPQ", "Assigned", 3, None),
("YZ3B4KED", "Assigned", 3, None),
("DHQMGF6M", "Assigned", 3, None),
("RGR58P4W", "Assigned", 3, None),
("GW29QPL9", "Assigned", 3, None),
("2Q9B8A7R", "Assigned", 3, None),
("ZTP48EH2", "Assigned", 3, None),
("6MGQ9GH9", "Assigned", 3, None),
("CGF3Z99F", "Assigned", 3, None),
("HE6H6C4J", "Assigned", 3, None),
("Q38P5J42", "Assigned", 3, None),
("6TD7TNUH", "Assigned", 3, None),
("FNP5XMW6", "Assigned", 3, None),
("RS2VHYYC", "Assigned", 3, None),
("NJGQGKLX", "Assigned", 3, None),
("3HQAP2D4", "Assigned", 3, None),
("V3VGF8SC", "Assigned", 3, None),
("FWLA27TV", "Assigned", 3, None),
("3H9Q2GR8", "Assigned", 3, None),
("KQ9YKXAC", "Assigned", 3, None),
("M8MB8JSN", "Assigned", 3, None),
("5LAUCATS", "Assigned", 3, None),
("8L6UD9XW", "Assigned", 3, None),
("TRMK968N", "Assigned", 3, None),
("CCM6RWZL", "Assigned", 3, None),
("M5BVGN45", "Assigned", 3, None),
("U49M5F7D", "Assigned", 3, None),
("MLDDGKUU", "Assigned", 3, None),
("69NWK8M2", "Assigned", 3, None),
("GHYVYZXE", "Assigned", 3, None),
("4YKDFRUB", "Assigned", 3, None),
("WEV9MAET", "Assigned", 3, None),
("7UBVXZKQ", "Assigned", 3, None),
("ETJF7ADG", "Assigned", 3, None),
("UAA44B22", "Assigned", 3, None),
("XP7YPE4Q", "Assigned", 3, None),
("HVVMR2YG", "Assigned", 3, None),
("J2T2JXVM", "Assigned", 3, None),
("GM9VR5XT", "Assigned", 3, None),
("V28WNAUQ", "Assigned", 3, None),
("VZXRQAAX", "Assigned", 3, None),
("C95BYRLC", "Assigned", 3, None),
("KZXRNFFQ", "Assigned", 3, None),
("2BSQ9HP7", "Assigned", 3, None),
("YWM2R4TP", "Assigned", 3, None),
("2QL43LL5", "Assigned", 3, None),
("L24MJYMX", "Assigned", 3, None),
("37C85DVE", "Assigned", 3, None),
("63J7C4B3", "Assigned", 3, None),
("UYQ2VCUJ", "Assigned", 3, None),
("3YTNN4N8", "Assigned", 3, None),
("ZW3HAKLR", "Assigned", 3, None),
("X547HLJZ", "Assigned", 3, None),
("FJBYLH93", "Assigned", 3, None),
("Z4YTC7WK", "Assigned", 3, None),
("X2JY3JRE", "Assigned", 3, None),
("32WZTZC3", "Assigned", 3, None),
("2PXKBRMZ", "Assigned", 3, None),
("Q7WJQUP4", "Assigned", 3, None),
("FBHND6V9", "Assigned", 3, None),
("35JKNK4F", "Assigned", 3, None),
("B2KBC8FE", "Assigned", 3, None),
("4D6LDKF5", "Assigned", 3, None),
("AGWRQE93", "Assigned", 3, None),
("Y6XE3R7K", "Assigned", 3, None),
("ZNTDPY97", "Assigned", 3, None),
("6BTBH9GZ", "Assigned", 3, None),
("UJVTPMZU", "Assigned", 3, None),
("2ZCPYZPF", "Assigned", 3, None),
("5YX9JLMW", "Assigned", 3, None),
("ZQ9TF7DF", "Assigned", 3, None),
("LXUUDVMC", "Assigned", 3, None),
("9ZG5HA7H", "Assigned", 3, None),
("KAKCXHR5", "Assigned", 3, None),
("HSRTK4BA", "Assigned", 3, None),
("VYSAJL7W", "Assigned", 3, None),
("JNUCNNHV", "Assigned", 3, None),
("63T8TQ3T", "Assigned", 3, None),
("94MGY5K3", "Assigned", 3, None),
("CJ3ZQ4QP", "Assigned", 3, None),
("J9YQR5VK", "Assigned", 3, None),
("T3952P72", "Assigned", 3, None),
("3JAD7TAD", "Assigned", 3, None),
("SWMG6TZJ", "Assigned", 3, None),
("8XNMDAXW", "Assigned", 3, None),
("LJC5XGA9", "Assigned", 3, None),
("VVUQG8BL", "Assigned", 3, None),
("C2DJRDUF", "Assigned", 3, None),
("8LC9BN79", "Assigned", 3, None),
("6ETKRD98", "Assigned", 3, None),
("4XUE74QH", "Assigned", 3, None),
("PA6LBM5E", "Assigned", 3, None),
("DQRJKXQ4", "Assigned", 3, None),
("3K8C89YU", "Assigned", 3, None),
("JYZAY85K", "Assigned", 3, None),
("KW9FTV8Z", "Assigned", 3, None),
("QWWG2RZK", "Assigned", 3, None),
("3MYA5VNC", "Assigned", 3, None),
("Z2BJ78MK", "Assigned", 3, None),
("HF82TF3Z", "Assigned", 3, None),
("LGHLK4QX", "Assigned", 3, None),
("J77WG366", "Assigned", 3, None),
("NELDNNA2", "Assigned", 3, None),
("BSXTQJRH", "Assigned", 3, None),
("7QFFHP9T", "Assigned", 3, None),
("F2U9YBQX", "Assigned", 3, None),
("4FPAMQAH", "Assigned", 3, None),
("N3T98E9X", "Assigned", 4, None),
("PXKHULDK", "Assigned", 4, None),
("NU8ZRMCM", "Assigned", 4, None),
("NSGY5QJG", "Assigned", 4, None),
("LZY6YAPX", "Assigned", 4, None),
("RR5R99P7", "Assigned", 4, None),
("EG7KNX3D", "Assigned", 4, None),
("JJE7WFHY", "Sold", 4, "09111274851"),
("6FTG7L2X", "Assigned", 4, None),
("5KWSBDJL", "Assigned", 4, None),
("5XQEEML3", "Assigned", 4, None),
("ZDDLHDNE", "Assigned", 4, None),
("33S97C5C", "Assigned", 4, None),
("U8Q3EBKR", "Assigned", 4, None),
("78J44877", "Assigned", 4, None),
("NR86P3Z6", "Assigned", 4, None),
("VXU7HNPR", "Assigned", 4, None),
("PFSBLJUH", "Assigned", 4, None),
("BV37XTXA", "Assigned", 4, None),
("KRHH2ZE3", "Assigned", 4, None),
("K29JXYWK", "Assigned", 4, None),
("83P2H3L8", "Assigned", 4, None),
("PQ6RPF8F", "Assigned", 4, None),
("9DCSPWE7", "Assigned", 4, None),
("HA7LHYG4", "Assigned", 4, None),
("R3FSMQXL", "Assigned", 4, None),
("7LGL3PBN", "Assigned", 4, None),
("8LUTKW9K", "Assigned", 4, None),
("75RCKLT5", "Assigned", 4, None),
("88FVMY26", "Assigned", 4, None),
("WHBEZ7ML", "Assigned", 4, None),
("2WLYF9D4", "Assigned", 4, None),
("HVKUK3K8", "Assigned", 4, None),
("CYAQUS6B", "Assigned", 4, None),
("5C6WLN3C", "Assigned", 4, None),
("QVLQW6HT", "Assigned", 4, None),
("RDYQCGFV", "Assigned", 4, None),
("NEXF2Q8G", "Assigned", 4, None),
("PQCGJHKD", "Assigned", 4, None),
("6EFL2VKG", "Assigned", 4, None),
("ULB2FU7Y", "Assigned", 4, None),
("5MEP2QTL", "Assigned", 4, None),
("P8A2ZZJW", "Assigned", 4, None),
("US8J7JWX", "Assigned", 4, None),
("ZPZ466VQ", "Assigned", 4, None),
("E6KJYBYT", "Assigned", 4, None),
("99GP6WMJ", "Assigned", 4, None),
("L5ZXMSLV", "Assigned", 4, None),
("97FVPJ24", "Assigned", 4, None),
("CD2HTPZE", "Assigned", 4, None),
("SQBUBSDJ", "Assigned", 4, None),
("6GTTDKUF", "Assigned", 4, None),
("WHC6J3TS", "Assigned", 4, None),
("H66TXFZH", "Assigned", 4, None),
("XNEG2G2U", "Assigned", 4, None),
("ZPZBZ7RB", "Assigned", 4, None),
("KZ7BYBJR", "Assigned", 4, None),
("AMKHD5G5", "Assigned", 4, None),
("NXBW357T", "Assigned", 4, None),
("VP95FCHS", "Assigned", 4, None),
("GDFW33N4", "Assigned", 4, None),
("BCMQNXGL", "Assigned", 4, None),
("8BAA38WC", "Assigned", 4, None),
("XQ4EH92M", "Assigned", 4, None),
("NVCVKN98", "Assigned", 4, None),
("TWHXVQGE", "Assigned", 4, None),
("LRS2NBXN", "Assigned", 4, None),
("T5Q6KL2P", "Assigned", 4, None),
("RMTBQJBY", "Assigned", 4, None),
("U2FG2NNM", "Assigned", 4, None),
("RNRZGCB4", "Assigned", 4, None),
("5GZ7KPU5", "Assigned", 4, None),
("NZYWL2HT", "Assigned", 4, None),
("CN3TK5TA", "Assigned", 4, None),
("WQA5HCUF", "Assigned", 4, None),
("7TJN37G4", "Assigned", 4, None),
("EWTQZMYY", "Assigned", 4, None),
("SSZJ7Y4H", "Assigned", 4, None),
("QHK36WJC", "Assigned", 4, None),
("KB6AAFMM", "Assigned", 4, None),
("QNGYBZGK", "Assigned", 4, None),
("S325WGM7", "Assigned", 4, None),
("CU3WCLMZ", "Assigned", 4, None),
("WV94RT2R", "Assigned", 4, None),
("3ZAWZGHR", "Assigned", 4, None),
("DK4FP96P", "Assigned", 4, None),
("9AUCBNHJ", "Assigned", 4, None),
("LHZK6X6F", "Assigned", 4, None),
("PSQGH67F", "Assigned", 4, None),
("YZKMQKN6", "Assigned", 4, None),
("C2F7923E", "Assigned", 4, None),
("VJSETAQM", "Assigned", 4, None),
("2SSLULD2", "Assigned", 4, None),
("9KECC7NL", "Assigned", 4, None),
("V5U9BXQQ", "Assigned", 4, None),
("ZVFBJNFJ", "Assigned", 4, None),
("P45FDRXC", "Assigned", 4, None),
("AXBFFJTK", "Assigned", 4, None),
("XCMSEZ6J", "Assigned", 4, None),
("L8XXYRX2", "Assigned", 4, None),
("PTZRVFPX", "Assigned", 4, None),
("A2KS43PT", "Assigned", 4, None),
("T4QEZXVG", "Assigned", 5, None),
("W752EF7E", "Assigned", 5, None),
("F69FXJAM", "Assigned", 5, None),
("PS2X64MY", "Assigned", 5, None),
("ZPZZN7LX", "Assigned", 5, None),
("GV87BK76", "Assigned", 5, None),
("4D4TCZVF", "Assigned", 5, None),
("JYP8TUGD", "Assigned", 5, None),
("KYF7ACQ9", "Assigned", 5, None),
("NMU67G7G", "Assigned", 5, None),
("WL39JS77", "Assigned", 5, None),
("LLUM46VW", "Assigned", 6, None),
("35JJRFPY", "Assigned", 6, None),
("43HUQGC8", "Assigned", 6, None),
("GEHH2T2Z", "Assigned", 6, None),
("M95FVS67", "Assigned", 6, None),
("KSU8LLY3", "Assigned", 6, None),
("8LQ26T7G", "Assigned", 6, None),
("N8DJFMLV", "Assigned", 6, None),
("DV69LNYV", "Assigned", 6, None),
("96ZE9EKU", "Assigned", 6, None),
("GP9P33NP", "Assigned", 6, None),
("6TZ9BSDU", "Assigned", 6, None),
("ZSNGGHH7", "Assigned", 6, None),
("PSQDJYAX", "Assigned", 6, None),
("FEEVMJD3", "Assigned", 6, None),
("PXDLC3E2", "Assigned", 6, None),
("HJFUSDJT", "Assigned", 7, None),
("HGGMJYC9", "Assigned", 7, None),
("8AYG8F5R", "Assigned", 7, None),
("TDUJAW4Q", "Assigned", 7, None),
("A2P2NRVR", "Assigned", 7, None),
("2GQULCHR", "Assigned", 8, None),
("CC8W2BUP", "Assigned", 8, None),
("82DFF8WP", "Assigned", 8, None),
("A4G6FVQ3", "Assigned", 8, None),
("7TN8MQUW", "Assigned", 9, None),
("PGYCUES4", "Assigned", 10, None),
("3XEL22YN", "Assigned", 16, None),
("2SD3A6TH", "Assigned", 16, None),
("36G969JJ", "Assigned", 16, None),
("QU83M6UX", "Assigned", 16, None),
("DEAHB8U8", "Assigned", 16, None),
("2EKV5R7C", "Assigned", 16, None),
("MUQ7YKCS", "Assigned", 16, None),
("5U2MH9JE", "Assigned", 16, None),
("B7HLJACF", "Assigned", 16, None),
("7QLR4E75", "Assigned", 16, None),
("FVXKQFA2", "Assigned", 16, None),
("P9297TQQ", "Assigned", 16, None),
("DV6NSG38", "Assigned", 16, None),
("FNM9C227", "Assigned", 16, None),
("QKANF3QV", "Assigned", 16, None),
("23DR7C67", "Assigned", 16, None),
("M7HMWJH9", "Assigned", 16, None),
("YB2JMNBF", "Assigned", 16, None),
("3HW263ZW", "Assigned", 16, None),
("U9ZWKMD7", "Assigned", 16, None),
("NWW3SZEV", "Assigned", 16, None),
("JXSXB7BL", "Assigned", 16, None),
("HVKVSLVB", "Assigned", 16, None),
("F5TFBY8J", "Assigned", 16, None),
("WHFP5GN8", "Assigned", 16, None),
("ZKEYATRD", "Assigned", 16, None),
("N9CWM5VL", "Assigned", 16, None),
("9RQK2PK8", "Assigned", 16, None),
("QQBKHCGC", "Assigned", 16, None),
("9GKK5R4F", "Assigned", 16, None),
("NCAA23AR", "Assigned", 16, None),
("D88JK94K", "Assigned", 16, None),
("9YSHZ86C", "Assigned", 16, None),
("5TRLZFX6", "Assigned", 16, None),
("J52BAQ23", "Assigned", 16, None),
("PW3JJJES", "Assigned", 16, None),
("HL54FJA3", "Assigned", 16, None),
("ZPXKRDDB", "Assigned", 16, None),
("S3W8NKWH", "Assigned", 16, None),
("WH6WJMX5", "Assigned", 16, None),
("DBHV5G2L", "Assigned", 16, None),
("MEM9AMDW", "Assigned", 16, None),
("DM5WE8FU", "Assigned", 16, None),
("PUMU2F33", "Assigned", 16, None),
("5KGCCMNG", "Assigned", 16, None),
("JTYUXGRA", "Assigned", 16, None),
("HRBPE7XG", "Assigned", 16, None),
("KQTAHX38", "Assigned", 16, None),
("FXMVHPXP", "Assigned", 16, None),
("U3L6BZBB", "Assigned", 16, None),
("VPSR4PHA", "Assigned", 17, None),
("MDM6TWBP", "Assigned", 17, None),
("RM9VCXXQ", "Assigned", 17, None),
("7FRER5ZR", "Assigned", 17, None),
("PQSCGGDF", "Assigned", 17, None),
("VK6GLYJ9", "Assigned", 17, None),
("S6TFZ9N7", "Assigned", 17, None),
("47L4GG9E", "Assigned", 17, None),
("ZVVKCXYN", "Assigned", 17, None),
("NP5MR25T", "Assigned", 17, None),
("SC9YA4S3", "Assigned", 17, None),
("56DKU4LX", "Assigned", 17, None),
("UK2KU7C8", "Assigned", 17, None),
("H27HN93Q", "Assigned", 17, None),
("NJC46G7Q", "Assigned", 17, None),
("U7QKJ3RD", "Assigned", 17, None),
("H7LTE6RJ", "Assigned", 17, None),
("Q48AEL6M", "Assigned", 17, None),
("TDC7T4R4", "Assigned", 17, None),
("QHDBDM59", "Assigned", 17, None),
("QM6BNTDF", "Assigned", 17, None),
("RTASSJ7U", "Assigned", 17, None),
("BHN2NP8M", "Assigned", 17, None),
("AQ7FS6KG", "Assigned", 17, None),
("KHTCRFDX", "Assigned", 17, None),
("H7CQRPN9", "Assigned", 17, None),
("PN7YSDNW", "Assigned", 17, None),
("BDHGTGAV", "Assigned", 17, None),
("8ENBU77Z", "Assigned", 17, None),
("WA7HCSHY", "Assigned", 17, None),
("ELCCQG3T", "Assigned", 17, None),
("PP8RYSYJ", "Assigned", 17, None),
("NPUC4HXT", "Assigned", 17, None),
("GKXJA3FF", "Assigned", 17, None),
("X6EMGCWH", "Assigned", 17, None),
("ZCWZAZLZ", "Assigned", 17, None),
("BJAK5N44", "Assigned", 17, None),
("PEH49WBU", "Assigned", 17, None),
("A7YJ9CGC", "Assigned", 17, None),
("UMWQ9GWA", "Assigned", 17, None),
("QEV7ZHGA", "Assigned", 17, None),
("FZ5WHWS5", "Assigned", 17, None),
("MW96W2W9", "Assigned", 17, None),
("YVMTYSQR", "Assigned", 17, None),
("VXWR6R7N", "Assigned", 17, None),
("AMHQNM87", "Assigned", 17, None),
("RDJJ6DSH", "Assigned", 17, None),
("M364FEEF", "Assigned", 17, None),
("PS6E5SPQ", "Assigned", 17, None),
("K4PFFNEJ", "Assigned", 17, None),
("PMK8A5GA", "Assigned", 17, None),
("TWAENGW3", "Assigned", 17, None),
("LL7LHASL", "Assigned", 17, None),
("HNGV9LDA", "Assigned", 17, None),
("TGA2QKUS", "Assigned", 18, None),
("FW9D49GZ", "Assigned", 18, None),
("69Y8DSG5", "Assigned", 18, None),
("3LSUF6FW", "Assigned", 18, None),
("T6ZAASJZ", "Assigned", 18, None),
("3UJJBUGC", "Assigned", 18, None),
("FJA6HT78", "Assigned", 18, None),
("YN6TN2AD", "Assigned", 18, None),
("8JHAPLHQ", "Assigned", 18, None),
("UF3FNW99", "Assigned", 18, None),
("3S69F987", "Assigned", 18, None),
("KTHUMGKQ", "Assigned", 18, None),
("H66NNKLR", "Assigned", 18, None),
("VLH6TZE8", "Assigned", 18, None),
("36AMX8EV", "Assigned", 18, None),
("AYGURNZE", "Assigned", 18, None),
("V9GTFNXQ", "Assigned", 18, None),
("UXNP93UU", "Assigned", 18, None),
("KCMTZBKT", "Assigned", 18, None),
("YWG4XBUN", "Assigned", 18, None),
("KDT59TTZ", "Assigned", 18, None),
("PM9LPVGL", "Assigned", 19, None),
("UKZK8ZGA", "Assigned", 19, None),
("MJ3A5Y4S", "Assigned", 19, None),
("QTRST7R7", "Assigned", 19, None),
("FMWVCEKP", "Assigned", 19, None),
("5T4W8VD8", "Assigned", 19, None),
("MZS8XJAL", "Assigned", 19, None),
("KGTZEDQE", "Assigned", 19, None),
("6VRRKRN3", "Assigned", 19, None),
("GZBZSDNQ", "Assigned", 19, None),
("9USR7H9J", "Assigned", 19, None),
("93PP85AT", "Assigned", 19, None),
("62KLYNAM", "Assigned", 19, None),
("K9RDA6X9", "Assigned", 19, None),
("489EEUTP", "Assigned", 19, None),
("ZJKFYEVY", "Assigned", 19, None),
("2423U7JP", "Assigned", 19, None),
("TR8Q24CM", "Assigned", 19, None),
("ND3WHAD6", "Assigned", 19, None),
("6M6DPHR6", "Assigned", 19, None),
("UAHD5FG8", "Assigned", 19, None),
("PMKMEPJ4", "Assigned", 19, None),
("82RHEUHK", "Assigned", 19, None),
("V4JFBVDB", "Assigned", 19, None),
("9WJ4TLVB", "Assigned", 19, None),
("Q8WG7A7U", "Assigned", 19, None),
("FFFK37R3", "Assigned", 20, None),
("JXWY8ZAT", "Assigned", 20, None),
("GVWNK98X", "Assigned", 20, None),
("2LZ7YTF3", "Assigned", 20, None),
("JXBLGCSC", "Assigned", 20, None),
("BKXNEJ6X", "Assigned", 20, None),
("8L8D5M4D", "Assigned", 20, None),
("PG2LFWZZ", "Assigned", 20, None),
]

RAW_BARS = [
    ("NEHBQ844", "2025-12-31 23:37:22.331163+03:30"),
    ("5JPSEHE4", "2026-02-20 22:26:52.988304+03:30"),
]


def main():
    print("=" * 60)
    print("TalaMala v4 - Old Bar Serial Migration")
    print("=" * 60)

    conn = engine.connect()
    trans = conn.begin()

    try:
        result = conn.execute(text("SELECT COUNT(*) FROM bars"))
        before_count = result.scalar()
        print("\nBars before migration: {}".format(before_count))

        result = conn.execute(text("SELECT id, mobile FROM users"))
        user_map = {row[1]: row[0] for row in result}
        print("Users in system: {}".format(len(user_map)))

        result = conn.execute(text("SELECT serial_code FROM bars"))
        existing_serials = {row[0] for row in result}
        print("Existing serials: {}".format(len(existing_serials)))

        inserted = 0
        skipped = 0
        sold_mapped = 0
        sold_unmapped = 0
        errors = []

        for serial, status, old_product_id, customer_mobile in OLD_BARS:
            if serial in existing_serials:
                skipped += 1
                continue

            new_product_id = PRODUCT_MAP.get(old_product_id)
            if new_product_id is None:
                skipped += 1
                continue

            customer_id = None
            if status == "Sold" and customer_mobile:
                customer_id = user_map.get(customer_mobile)
                if customer_id:
                    sold_mapped += 1
                else:
                    sold_unmapped += 1
                    print("  [WARN] Sold bar {}: customer {} not found in users".format(serial, customer_mobile))

            try:
                conn.execute(
                    text("""
                        INSERT INTO bars (serial_code, status, product_id, customer_id, batch_id, created_at)
                        VALUES (:serial, :status, :product_id, :customer_id, 1, now())
                    """),
                    {
                        "serial": serial,
                        "status": status,
                        "product_id": new_product_id,
                        "customer_id": customer_id,
                    }
                )
                inserted += 1
                existing_serials.add(serial)
            except Exception as e:
                errors.append((serial, str(e)))
                print("  [ERROR] Bar {}: {}".format(serial, e))

        for serial, created_at in RAW_BARS:
            if serial in existing_serials:
                skipped += 1
                continue
            try:
                conn.execute(
                    text("""
                        INSERT INTO bars (serial_code, status, product_id, batch_id, created_at)
                        VALUES (:serial, 'Raw', NULL, NULL, :created_at)
                    """),
                    {"serial": serial, "created_at": created_at}
                )
                inserted += 1
            except Exception as e:
                errors.append((serial, str(e)))
                print("  [ERROR] Raw bar {}: {}".format(serial, e))

        trans.commit()

        result = conn.execute(text("SELECT COUNT(*) FROM bars"))
        after_count = result.scalar()

        result = conn.execute(text(
            "SELECT serial_code, status, product_id, customer_id FROM bars "
            "WHERE serial_code IN ('94LEXNLL', 'JJE7WFHY', '68GFDFFE', 'NEHBQ844', 'FYW2H8MQ')"
        ))
        sample_bars = result.fetchall()

        print("\n" + "=" * 60)
        print("MIGRATION COMPLETE")
        print("=" * 60)
        print("  Inserted:        {}".format(inserted))
        print("  Skipped (exist): {}".format(skipped))
        print("  Sold -> mapped:  {}".format(sold_mapped))
        print("  Sold -> unmapped:{}".format(sold_unmapped))
        print("  Errors:          {}".format(len(errors)))
        print("  Bars before:     {}".format(before_count))
        print("  Bars after:      {}".format(after_count))
        print("  Net added:       {}".format(after_count - before_count))

        if sample_bars:
            print("\nSample verification:")
            for row in sample_bars:
                print("  {} | status={} | product_id={} | customer_id={}".format(row[0], row[1], row[2], row[3]))

        if errors:
            print("\nERRORS ({})".format(len(errors)))
            for serial, err in errors:
                print("  {}: {}".format(serial, err))
            return 1

        print("\nAll old bar serials are now searchable in /verify/check")
        return 0

    except Exception as e:
        trans.rollback()
        print("\n[FATAL] Migration failed, rolled back: {}".format(e))
        import traceback
        traceback.print_exc()
        return 1
    finally:
        conn.close()


if __name__ == "__main__":
    sys.exit(main())
